homework00: Introduce yourself
==============================

Due date:: End of day, 22 Jan 2015

Objectives
----------

The purpose of this assignment is twofold:

1. Introduce yourself to me so that I can better understand your background and what you hope to get from this course.
2. Become familiar with the homework submission process

Muhammet Onur Oksuz

I'm Onur Oksuz

I'm currently attending to North American University. My major is Computer Science. I like to develop and create new things. I mostly code on the web, using Java programming language. I'm improving myself everyday with the classes that I enroll at North American University. I do practice my classes every Tuesday and Thursday at Rice University Library. On Sundays and Thursdays I go to GYM and do my workout.
<p>I spend at least three hours a day working on web development. I enrolled the following classes, Javascript, PHP, HTML. CSS at codeacademy.com. Also I'm following the Laracasts's video tutorials about PHP language.</p>

My Hobbies

Playing with PSP.
Watching and playing soccer.
Watching Tv Series.
